bootstrap-admin-username=admin
bootstrap-admin-password=password

http-enabled=true
http-management-health-enabled=true
http-relative-path=/idp
http-management-scheme=http
hostname=https://localhost/idp
hostname-backchannel-dynamic=true
https-certificate-file=/etc/ssl/certs/keycloak.tls.crt
https-certificate-key-file=/etc/ssl/certs/keycloak.tls.key
proxy-headers=forwarded
health-enabled=true

spi-signature--ES256--enabled=true
spi-signature--ES384--enabled=true
spi-signature--ES512--enabled=true
spi-signature--Ed-dSA--enabled=false
spi-signature--RS256--enabled=true
spi-signature--RS384--enabled=true
spi-signature--RS512--enabled=true
spi-signature--PS256--enabled=true
spi-signature--PS384--enabled=true
spi-signature--PS512--enabled=true
spi-signature--HS256--enabled=true
spi-signature--HS384--enabled=true
spi-signature--HS512--enabled=true

spi-client-signature--ES256--enabled=true
spi-client-signature--ES384--enabled=true
spi-client-signature--ES512--enabled=true
spi-client-signature--Ed-dSA--enabled=false
spi-client-signature--RS256--enabled=true
spi-client-signature--RS384--enabled=true
spi-client-signature--RS512--enabled=true
spi-client-signature--PS256--enabled=true
spi-client-signature--PS384--enabled=true
spi-client-signature--PS512--enabled=true
spi-client-signature--HS256--enabled=true
spi-client-signature--HS384--enabled=true
spi-client-signature--HS512--enabled=true

spi-contentencryption--A128GCM--enabled=true
spi-contentencryption--A192GCM--enabled=true
spi-contentencryption--A256GCM--enabled=true
spi-contentencryption--A128CBC-HS256--enabled=true
spi-contentencryption--A192CBC-HS384--enabled=true
spi-contentencryption--A256CBC-HS512--enabled=true

spi-cekmanagement--ECDH-ES--enabled=true
spi-cekmanagement--ECDH-ES+A128KW--enabled=true
spi-cekmanagement--ECDH-ES+A192KW--enabled=true
spi-cekmanagement--ECDH-ES+A256KW--enabled=true
spi-cekmanagement--RSA1_5--enabled=false
spi-cekmanagement--RSA-OAEP--enabled=false
spi-cekmanagement--RSA-OAEP-256--enabled=true