logging.level.org.springframework=info

spring.main.web-application-type=reactive
spring.webflux.static-path-pattern=/public/**
spring.webflux.webjars-path-pattern=/webjars/**
spring.messages.basename=i18n/messages
server.forward-headers-strategy=framework
spring.http.codecs.max-in-memory-size=1MB

#
# Issuer options
#
issuer.credentialRequestEncryption.supported=true
issuer.credentialRequestEncryption.required=true
issuer.credentialRequestEncryption.jwks.algorithm=ECDH-ES
issuer.credentialRequestEncryption.encryptionMethods=A128GCM,A256GCM
issuer.credentialRequestEncryption.zipAlgorithmsSupported=
issuer.credentialResponseEncryption.supported=true
issuer.credentialResponseEncryption.required=true
issuer.credentialResponseEncryption.algorithmsSupported=ECDH-ES
issuer.credentialResponseEncryption.encryptionMethods=A128GCM,A256GCM
issuer.credentialResponseEncryption.zipAlgorithmsSupported=

issuer.pid.mso_mdoc.enabled=true
issuer.pid.mso_mdoc.encoder.duration=P31D
issuer.pid.mso_mdoc.notifications.enabled=true
issuer.pid.mso_mdoc.proofs.supportedSigningAlgorithms=ES256

issuer.pid.sd_jwt_vc.enabled=true
issuer.pid.sd_jwt_vc.duration=P31D
issuer.pid.sd_jwt_vc.notUseBefore=PT20S
issuer.pid.sd_jwt_vc.notifications.enabled=true
issuer.pid.sd_jwt_vc.digests.hashAlgorithm=sha-256
issuer.pid.sd_jwt_vc.proofs.supportedSigningAlgorithms=ES256

issuer.pid.issuingCountry=GR
issuer.pid.issuingJurisdiction=GR-I

issuer.mdl.enabled=true
issuer.mdl.mso_mdoc.encoder.duration=P31D
issuer.mdl.notifications.enabled=true
issuer.mdl.proofs.supportedSigningAlgorithms=ES256

issuer.learningCredential.enabled=true
issuer.learningCredential.sdJwtVc.encoder.digests.hashAlgorithm=sha-256
issuer.learningCredential.validity=P31D
issuer.learningCredential.notifications.enabled=true
issuer.learningCredential.proofs.supportedSigningAlgorithms=ES256

issuer.credentialOffer.defaultUri=eu-eaa-offer://
issuer.credentialOffer.allowedSchemes=https,eu-eaa-offer

issuer.sd-jwt-vc.type-metadata[0].vct=urn:eudi:pid:1
issuer.sd-jwt-vc.type-metadata[0].resource=classpath:/vct/pid_v1.4.json
issuer.sd-jwt-vc.type-metadata[1].vct=urn:eu.europa.ec.eudi:learning:credential:1
issuer.sd-jwt-vc.type-metadata[1].resource=classpath:/vct/learning_credential.json

issuer.dpop.nonce.enabled=true
issuer.dpop.nonce.expiration=PT5M

issuer.credentialEndpoint.batchIssuance.enabled=true
issuer.credentialEndpoint.batchIssuance.batchSize=20
issuer.metadata.preferred-client-status-period=P31D
issuer.cnonce.expiration=PT5M
issuer.revocationJob.cron=0 * */8 * * *

#
# Resource Server configuration
#
spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=${issuer.authorizationServer.introspection}

#
# Proxy settings
#
#issuer.http.proxy.url=http://example.com
#issuer.http.proxy.username=test
#issuer.http.proxy.password=test

#
# Persistence
#
spring.sql.init.mode=never