spring.web.error.include-stacktrace=always

#
# Issuer options
#
issuer.publicUrl=http://localhost:8080
issuer.authorizationServer.publicUrl=https://localhost/idp/realms/pid-issuer-realm
issuer.authorizationServer.introspection=${issuer.authorizationServer.publicUrl}/protocol/openid-connect/token/introspect

issuer.keystore.file=classpath:issuer-keys.jks
issuer.keystore.type=JKS
issuer.keystore.password=keys

issuer.credentialRequestEncryption.jwks.alias=request-encryption
issuer.credentialRequestEncryption.jwks.password=request-encryption

issuer.nonce.encryption-key.alias=nonce-encryption
issuer.nonce.encryption-key.password=nonce-encryption

issuer.pid.mso_mdoc.signing-key.alias=issuance
issuer.pid.mso_mdoc.signing-key.password=issuance
issuer.pid.sd_jwt_vc.signing-key.alias=issuance
issuer.pid.sd_jwt_vc.signing-key.password=issuance

issuer.mdl.signing-key.alias=issuance
issuer.mdl.signing-key.password=issuance

issuer.learningCredential.signing-key.alias=issuance
issuer.learningCredential.signing-key.password=issuance

issuer.dpop.realm=pid-issuer

issuer.access-certificate.alias=access-certificate
issuer.access-certificate.password=access-certificate

issuer.metadata.display[0].name=Digital Credentials Issuer
issuer.metadata.display[0].locale=en
issuer.metadata.display[0].logo.uri=https://eudiw.dev/ic-logo.svg
issuer.metadata.display[0].logo.alternative-text=EU Digital Identity Wallet Logo
issuer.metadata.display[1].name=\u0395\u03ba\u03b4\u03cc\u03c4\u03b7\u03c2 \u03a8\u03b7\u03c6\u03b9\u03b1\u03ba\u03ce\u03bd \u0394\u03b9\u03b1\u03c0\u03b9\u03c3\u03c4\u03b5\u03c5\u03c4\u03b7\u03c1\u03af\u03c9\u03bd
issuer.metadata.display[1].locale=el
issuer.metadata.display[1].logo.uri=https://eudiw.dev/ic-logo.svg
issuer.metadata.display[1].logo.alternative-text=\u039b\u03bf\u03b3\u03cc\u03c4\u03c5\u03c0\u03bf \u0395\u03c5\u03c1\u03c9\u03c0\u03b1\u03ca\u03ba\u03bf\u03cd \u03a0\u03bf\u03c1\u03c4\u03bf\u03c6\u03bf\u03bb\u03b9\u03bf\u03cd \u03a8\u03b7\u03c6\u03b9\u03b1\u03ba\u03ae\u03c2 \u03a4\u03b1\u03c5\u03c4\u03cc\u03c4\u03b7\u03c4\u03b1\u03c2

issuer.statusList.service.generate-uri=https://localhost/token_status_list/take
issuer.statusList.service.revoke-uri=https://localhost/token_status_list/set
issuer.statusList.service.apiKey=aaa-bbb-ccc

#
# Resource Server configuration
#
spring.security.oauth2.resourceserver.opaquetoken.client-id=pid-issuer-srv
spring.security.oauth2.resourceserver.opaquetoken.client-secret=zIKAV9DIIIaJCzHCVBPlySgU8KgY68U2

#
# Keycloak configuration
#
issuer.keycloak.server-url=https://localhost/idp
issuer.keycloak.authentication-realm=master
issuer.keycloak.client-id=admin-cli
issuer.keycloak.username=admin
issuer.keycloak.password=password
issuer.keycloak.user-realm=pid-issuer-realm

#
# Persistence
#
spring.r2dbc.url=r2dbc:pool:postgresql://pid_issuer:pid_issuer@localhost:5432/pid_issuer

# Trust Configuration
issuer.trust.service-url=

issuer.wrprc=eyJ4NWMiOlsiTUlJQkhEQ0J4S0FEQWdFQ0FoUmp6T3Z1VUNXNFVieXMyNWgvRndHZlN4SFR1akFLQmdncWhrak9QUVFEQWpBUE1RMHdDd1lEVlFRRERBUjBaWE4wTUI0WERUSTJNRGN4TURBNE1EZ3dOMW9YRFRJM01EY3hNREE0TURnd04xb3dEekVOTUFzR0ExVUVBd3dFZEdWemREQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJKZlY0dFJ5U1dybTdsVkFTQjk0bUJLTTR3dlBKRkV1S012VWhwcUlyY3JkMkduam1PejJJS3Vrb0tkZVRjbTkzczM5U2w1NHl4UTI0Q3NLTVlmM2t3c3dDZ1lJS29aSXpqMEVBd0lEUndBd1JBSWdhdFJ6eUVidklLWk9wNVlyUDlJYW5ScVcyRTk1dC9vM3F1cmV0OXVXY2hrQ0lIcndEQ3dwQlJKNk9LQUNrZmNGRVZvWmNiTTU4NGZpRjVzb2h1TXNLcjg3Il0sInR5cCI6InJjLXdycCtqd3QiLCJhbGciOiJFUzI1NiJ9.eyJuYW1lIjoiS290bGluIElzc3VlciBTaWduZXIgRGV2Iiwic3ViX2xuIjoiTmlzY3kiLCJzdWIiOiJMRUlFVS0xMjM0NTY3ODkiLCJjb3VudHJ5IjoiRVUiLCJyZWdpc3RyeV91cmkiOiJodHRwczovL3JlZ2lzdHJ5LmV4YW1wbGUuZXUiLCJzcnZfZGVzY3JpcHRpb24iOlt7ImxhbmciOiJlbiIsInZhbHVlIjoiQW4gaW1wbGVtZW50YXRpb24gb2YgYSBjcmVkZW50aWFsIGlzc3Vpbmcgc2VydmljZSwgYWNjb3JkaW5nIHRvIE9wZW5JZDRWQ0kgLSB2MS4wIn1dLCJlbnRpdGxlbWVudHMiOlsiaHR0cHM6Ly91cmkuZXRzaS5vcmcvMTk0NzUvRW50aXRsZW1lbnQvUElEX1Byb3ZpZGVyIiwiaHR0cHM6Ly91cmkuZXRzaS5vcmcvMTk0NzUvRW50aXRsZW1lbnQvUUVBQV9Qcm92aWRlciIsImh0dHBzOi8vdXJpLmV0c2kub3JnLzE5NDc1L0VudGl0bGVtZW50L1BVQl9FQUFfUHJvdmlkZXIiXSwicHJpdmFjeV9wb2xpY3kiOiJodHRwczovL2Rldi5pc3N1ZXItYmFja2VuZC5ldWRpdy5kZXYvcHJpdmFjeSIsImluZm9fdXJpIjoiaHR0cHM6Ly9kZXYuaXNzdWVyLWJhY2tlbmQuZXVkaXcuZGV2Iiwic3VwcG9ydF91cmkiOiJodHRwczovL2Rldi5rb3RsaW5Jc3N1ZXJTaWduZXIuY29tL3N1cHBvcnQiLCJzdXBlcnZpc29yeV9hdXRob3JpdHkiOnsiZW1haWwiOiJzdXBlcnZpc29yeUBhdXRob3JpdHkuZXhhbXBsZS5ldSIsInBob25lIjoiKzQ5MzAxMjM0NTY3IiwidXJpIjoiaHR0cHM6Ly9zdXBlcnZpc29yeS5hdXRob3JpdHkuZXhhbXBsZS5ldSJ9LCJwb2xpY3lfaWQiOlsiMC40LjAuMTk0NzUuMy4xIl0sImNlcnRpZmljYXRlX3BvbGljeSI6Imh0dHBzOi8vZXhhbXBsZS5ldS9jZXJ0aWZpY2F0ZS1wb2xpY3kiLCJpYXQiOjE3ODM2ODEwMjgsInN0YXR1cyI6eyJzdGF0dXNfbGlzdCI6eyJpZHgiOjkxMCwidXJpIjoiaHR0cHM6Ly9pc3N1ZXIuZXVkaXcuZGV2L3Rva2VuX3N0YXR1c19saXN0L0VVL2V1LmV1cm9wYS5lYy5ldWRpLnBpZC4xLzIwZWY5ZTk4LTg2NzYtNDViYy04OWJhLTE3MDhmMGYyMTIzOSJ9fSwicHJvdmlkZXNfYXR0ZXN0YXRpb25zIjpbeyJmb3JtYXQiOiJkYytzZC1qd3QiLCJtZXRhIjp7InZjdF92YWx1ZXMiOlsidXJuOmV1ZGk6cGlkOjEiLCJ1cm46ZXUuZXVyb3BhLmVjLmV1ZGk6bGVhcm5pbmc6Y3JlZGVudGlhbDoxIl19fSx7ImZvcm1hdCI6Im1zb19tZG9jIiwibWV0YSI6eyJkb2N0eXBlX3ZhbHVlIjoiZXUuZXVyb3BhLmVjLmV1ZGkucGlkLjEifX0seyJmb3JtYXQiOiJtc29fbWRvYyIsIm1ldGEiOnsiZG9jdHlwZV92YWx1ZSI6Im9yZy5pc28uMTgwMTMuNS4xLm1ETCJ9fV19.h3wtRbSVXVGJVblxwHLQQivFN-iQiyyIGLmbFoNHpC8GRcKjuseUhbatzS-PGh7eDBPOCwh0VSgotEtjTiYKzA