version: '3.8'

networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgres:18.4-alpine3.24
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=pid_issuer
      - POSTGRES_USER=pid_issuer
      - POSTGRES_PASSWORD=pid_issuer
    volumes:
      - postgres:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pid_issuer -d pid_issuer" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - default

  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
      args:
        VERSION: ${KEYCLOAK_ABCA_EXTENSION_VERSION}
    image: keycloak-abca:${KEYCLOAK_ABCA_EXTENSION_VERSION}
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
      - --features=dpop,passkeys
    environment:
      - KC_PROXY_HEADERS=forwarded
      - KC_HTTP_ENABLED=true
      - KC_HTTP_RELATIVE_PATH=/idp
      - KC_HOSTNAME=https://localhost/idp
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - KC_HTTPS_CERTIFICATE_FILE=/etc/ssl/certs/keycloak.tls.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/ssl/certs/keycloak.tls.key
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=password
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "{ printf 'HEAD /idp/health/ready HTTP/1.0\r\n\r\n' >&0; grep 'HTTP/1.0 200'; } 0<>/dev/tcp/localhost/9000"
        ]
      interval: 5s
      timeout: 10s
      retries: 12
      start_interval: 30s
      start_period: 30s
    volumes:
      - ./keycloak/realms/:/opt/keycloak/data/import
      - ./keycloak/certs/:/etc/ssl/certs/
      - ./keycloak/conf/keycloak.conf:/opt/keycloak/conf/keycloak.conf
    networks:
      - default

  status-list:
    build:
      context: ./status-list
      dockerfile: Dockerfile
      args:
        VERSION: ${STATUS_LIST_VERSION}
    image: status-list:${STATUS_LIST_VERSION}
    container_name: status-list
    environment:
      API_key: aaa-bbb-ccc
    volumes:
      - ./status-list/config/config_service.py:/status-list/app/config_service.py
      - ./status-list/certs:/status-list/certs
      - status-lists:/var/opt/status_lists
      - status-lists-backups:/var/opt/status_list_backup
    networks:
      - default

  pid-issuer:
    image: ghcr.io/eu-digital-identity-wallet/eudi-srv-pid-issuer:edge
    pull_policy: always
    container_name: pid-issuer
    depends_on:
      keycloak:
        condition: service_healthy
      postgres:
        condition: service_healthy
      status-list:
        condition: service_started
    environment:
      - SPRING_PROFILES_ACTIVE=insecure
      - SPRING_WEBFLUX_BASE_PATH=/pid-issuer
      - SERVER_PORT=8080
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_ID=pid-issuer-srv
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_SECRET=zIKAV9DIIIaJCzHCVBPlySgU8KgY68U2
      - SERVER_FORWARD_HEADERS_STRATEGY=FRAMEWORK
      - ISSUER_PUBLICURL=https://localhost/pid-issuer
      - ISSUER_AUTHORIZATIONSERVER_PUBLICURL=https://localhost/idp/realms/pid-issuer-realm
      - ISSUER_AUTHORIZATIONSERVER_METADATA=https://keycloak:8443/idp/realms/pid-issuer-realm/.well-known/openid-configuration
      - ISSUER_AUTHORIZATIONSERVER_INTROSPECTION=https://keycloak:8443/idp/realms/pid-issuer-realm/protocol/openid-connect/token/introspect
      - ISSUER_CREDENTIALRESPONSEENCRYPTION_SUPPORTED=true
      - ISSUER_CREDENTIALRESPONSEENCRYPTION_REQUIRED=true
      - ISSUER_CREDENTIALRESPONSEENCRYPTION_ALGORITHMSSUPPORTED=ECDH-ES
      - ISSUER_CREDENTIALRESPONSEENCRYPTION_ENCRYPTIONMETHODS=A128GCM
      - ISSUER_PID_MSO_MDOC_ENABLED=true
      - ISSUER_PID_MSO_MDOC_ENCODER_DURATION=P31D
      - ISSUER_PID_MSO_MDOC_NOTIFICATIONS_ENABLED=true
      - ISSUER_PID_SD_JWT_VC_ENABLED=true
      - ISSUER_PID_SD_JWT_VC_NOTUSEBEFORE=PT20S
      - ISSUER_PID_SD_JWT_VC_NOTIFICATIONS_ENABLED=true
      - ISSUER_PID_ISSUINGCOUNTRY=GR
      - ISSUER_PID_ISSUINGJURISDICTION=GR-I
      - ISSUER_MDL_ENABLED=true
      - ISSUER_MDL_MSO_MDOC_ENCODER_DURATION=P5D
      - ISSUER_MDL_NOTIFICATIONS_ENABLED=true
      - ISSUER_CREDENTIALOFFER_URI=openid-credential-offer://
      - ISSUER_SIGNING_KEY=GenerateRandom
      - ISSUER_KEYCLOAK_SERVER_URL=https://keycloak:8443/idp
      - ISSUER_KEYCLOAK_AUTHENTICATION_REALM=master
      - ISSUER_KEYCLOAK_CLIENT_ID=admin-cli
      - ISSUER_KEYCLOAK_USERNAME=admin
      - ISSUER_KEYCLOAK_PASSWORD=password
      - ISSUER_KEYCLOAK_USER_REALM=pid-issuer-realm
      - ISSUER_DPOP_REALM=pid-issuer
      - ISSUER_DPOP_NONCE_ENABLED=false
      - ISSUER_CREDENTIALENDPOINT_BATCHISSUANCE_ENABLED=true
      - ISSUER_CREDENTIALENDPOINT_BATCHISSUANCE_BATCHSIZE=10
      - ISSUER_CNONCE_EXPIRATION=PT5M
      - SPRING_R2DBC_URL=r2dbc:pool:postgresql://postgres:5432/pid_issuer
      - SPRING_R2DBC_USERNAME=pid_issuer
      - SPRING_R2DBC_PASSWORD=pid_issuer
      - ISSUER_STATUSLIST_SERVICE_GENERATE_URI=http://status-list:5000/token_status_list/take
      - ISSUER_STATUSLIST_SERVICE_REVOKE_URI=http://status-list:5000/token_status_list/take
      - ISSUER_STATUSLIST_SERVICE_APIKEY=aaa-bbb-ccc
    networks:
      - default

  haproxy:
    image: haproxy:2.8.3
    container_name: haproxy
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      keycloak:
        condition: service_healthy
      pid-issuer:
        condition: service_started
      status-list:
        condition: service_started
    volumes:
      - ./haproxy/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
      - ./haproxy/certs/:/etc/ssl/certs/
    networks:
      - default

volumes:
  status-lists:
  status-lists-backups:
  postgres:
